on: [push, workflow_dispatch]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
          - os: ubuntu-22.04-arm
          - os: ubuntu-24.04
          - os: ubuntu-24.04
            sysctl: true
          - os: ubuntu-24.04-arm
          - os: ubuntu-24.04-arm
            sysctl: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - if: ${{ matrix.sysctl == true }}
        run: sudo sysctl kernel/apparmor_restrict_unprivileged_userns=0
      - run: pnpm install
      - run: pnpm run start
        env:
          DEBUG: pw:browser*
